### ISSUE TITLE
What is the need for Kafka and ZooKeeper in Blogging System ?

### ISSUE THREAD

**Issue by hackwithharsha** [abhishekgupta368/week1-blogging-system#1]
I am assuming, You might to be using Elastic Search as a primary database which will provide search capabilities along with improved latency for read queries..

However, can you elaborate little bit how you are using zookeeper and kafka in this architecture ?

**Comment by abhishekgupta368** [comment]
Sure, I will do it

**Comment by abhishekgupta368** [comment]
I t  is solved.
